//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int GiverId { get; set; }
        public int ActionId { get; set; }
        public int UserId { get; set; }
        public int WarehouseId { get; set; }
        public System.DateTime Date { get; set; }
        public double Quantity { get; set; }
    
        public virtual ActionsDictionary ActionsDictionary { get; set; }
        public virtual GiversDictionary GiversDictionary { get; set; }
        public virtual ProductDictionariy ProductDictionariy { get; set; }
        public virtual User User { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
