//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehouseEntities1 : DbContext
    {
        public WarehouseEntities1()
            : base("name=WarehouseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionsDictionary> ActionsDictionaries { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<CategoryDictionary> CategoryDictionaries { get; set; }
        public virtual DbSet<GiversDictionary> GiversDictionaries { get; set; }
        public virtual DbSet<NetoDictionary> NetoDictionaries { get; set; }
        public virtual DbSet<ProductDictionariy> ProductDictionariys { get; set; }
        public virtual DbSet<ProductPlace> ProductPlaces { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StatusDictionary> StatusDictionaries { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
    }
}
